version: '3'
services:
  nginx:
    container_name: nginx
    build: ./nginx/
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    networks:
      - transcendence-net
    volumes:
      - nginx-vol:/var/www/
    restart: on-failure

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres-vol:/var/lib/postgresql/data
    networks:
      - transcendence-net
    restart: unless-stopped

volumes:
  postgres-vol:
    name: postgres-vol
  nginx-vol:
    name: nginx-vol
    driver: local
    driver_opts:
      type: none
      o: bind
      device: "./nginx/www/"

networks:
  transcendence-net:
    name: transcendence-net
    driver: bridge
