version: '3'
services:
  nginx:
    container_name: nginx
    build: ./nginx/
    image: nginx-transcedence
    env_file:
      - .env
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - django
    networks:
      - transcendence-net
    volumes:
      - ./nginx/www:/var/www/
    restart: on-failure

  django:
    container_name: django
    build: ./django
    image: django-transcendence
    env_file:
      - .env
    expose:
      - 8000
    depends_on:
      - postgres
    networks:
      - transcendence-net
    volumes:
      - ./django/transcendence:/var/src/app

  postgres:
    image: postgres:latest
    container_name: postgres
    env_file:
      - .env
    volumes:
      - postgres-vol:/var/lib/postgresql/data/
    networks:
      - transcendence-net
    restart: unless-stopped

  serverpong:
    container_name: serverpong
    build: ./serverPong
    image: django-serverpong
    env_file:
      - .env
    ports:
      - "10000:10000"
    networks:
      - transcendence-net
    volumes:
      - serverPong-vol:/var/src/app

volumes:
  postgres-vol:
    name: postgres-vol
  nginx-vol:
    name: nginx-vol
  django-vol:
    name: django-vol
  serverPong-vol:
    name: serverPong-vol

networks:
  transcendence-net:
    name: transcendence-net
    driver: bridge

