# Generated by Django 5.0.1 on 2024-02-21 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('friends', '0002_alter_friendship_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='friendship',
            name='date_added',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
