# Generated by Django 5.0.1 on 2024-02-20 15:05

import django.db.models.deletion
import userprofile.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('profile_picture', models.ImageField(upload_to=userprofile.models.generate_image_uuid)),
                ('online_status', models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Away', 'Away'), ('Playing', 'Playing')], default='Offline', max_length=20)),
                ('otp_active', models.BooleanField(default=False)),
                ('otp_key', models.CharField(default='', max_length=32)),
                ('otp_previous', models.CharField(default='', max_length=6)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
