# Generated by Django 5.0.1 on 2024-02-15 14:15

import userprofile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(upload_to=userprofile.models.generate_image_uuid),
        ),
    ]
