# Generated by Django 5.0.1 on 2024-02-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='online_status',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Away', 'Away')], default='Offline', max_length=20),
        ),
    ]
