# Generated by Django 5.0.1 on 2024-02-28 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_profile_channel_name'),
        ('userprofile', '0002_profile_oauth_42_access_profile_oauth_42_active_and_more'),
    ]

    operations = [
    ]
