# Generated by Django 5.0.1 on 2024-02-16 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0002_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='otp_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='profile',
            name='otp_key',
            field=models.CharField(default='', max_length=32),
        ),
        migrations.AddField(
            model_name='profile',
            name='otp_previous',
            field=models.CharField(default='', max_length=6),
        ),
    ]
