# Generated by Django 5.0.1 on 2024-03-04 21:25

import userprofile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_merge_20240228_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='images/avatar.png', upload_to=userprofile.models.generate_image_uuid),
        ),
    ]
