# Generated by Django 5.0.1 on 2024-02-20 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0003_profile_online_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='online_status',
            field=models.CharField(choices=[('Online', 'Online'), ('Offline', 'Offline'), ('Away', 'Away'), ('Playing', 'Playing')], default='Offline', max_length=20),
        ),
    ]
