# Generated by Django 5.0.1 on 2024-03-05 15:39

import userprofile.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('userprofile', '0004_alter_profile_profile_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_picture',
            field=models.ImageField(default='default/avatar.png', upload_to=userprofile.models.generate_image_uuid),
        ),
    ]
